### ISSUE TITLE
Testing that functionality of validating the CSV is still working

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/interactive-management-app#18]

**Comment by Alyssa4854** [comment]
Will begin work on tests once other/basic functionality is implemented and available to test

**Comment by kefortney** [comment]
Can you move it back to Backlog (if you think it will not be worked on this sprint) or to Ready (if you think you might get what you need to work on it)?

**Comment by Alyssa4854** [comment]
Worked out an example Python unittest to build off of/model future tests from.

I created a single test verifying that Issue17 works OK; including patching input/automation. There isn't much else I can do now, but I wanted to get a sort of "sample" created so that making future tests will be easier, and we will be able to know when a function/issue is "complete" easier

**Comment by Alyssa4854** [comment]
For now, I have the tests in the best state I feel they can be; will revise later
